pretrain:
  enc_checkpoint_key: model
  pred_checkpoint_key: null
  model_name: pretrain_videomae_base_patch16_224_ep2400_ssv2
  patch_size: 16
  folder: /home/diego.canez/checkpoints/intphys/videomae
  checkpoint: ssv2-vitb-ep2400.pth
  write_tag: videomaev1_ep2400_ssv2_vitb
  frames_per_clip: 16
data:
  batch_size: 1
  resolution: 224
  stride_sliding_window: 2
  use_bfloat16: true
  frames_per_clip: 16
  context_lengths: [2,4,6,8,10]
  frame_steps: 2
tag: videomaev1_ep2400_ssv2_vitb
nodes: 1
tasks_per_node: 1
eval_name: intuitive_physics
dataset: intphys
is_mae: true
mae_decoder_blocks: -1