# @package model

defaults:
  - /model/sigma/vitb_dino
  - override /model/sigma/target_encoder@net.target_encoder: mlp

net:
  target_type: "mlp"
  encoder:
    num_prototypes: 4000 # this
    eps: 0.05
