# @package model

defaults:
  - /model/sigma/target_encoder@net.target_encoder: dino

net:
  _target_: intphyseval.model.sigma.net.SIGMA
  num_frames: ${model.net.patch_size}
  img_size: 224
  patch_size: 16
  target_type: "dino_v1" # dino_v1 or mlp
  loss_func: "SWAV"

  encoder:
    _target_: intphyseval.model.sigma.net.PretrainVisionTransformer
    img_size: ${model.net.img_size}
    patch_size: ${model.net.patch_size}
    encoder_embed_dim: 768
    encoder_depth: 12
    encoder_num_heads: 12
    encoder_num_classes: 0
    decoder_embed_dim: 384
    decoder_num_heads: 6
    mlp_ratio: 4
    qkv_bias: True
    norm_layer: 
      _target_: torch.nn.LayerNorm
      _partial_: true
      eps: 1e-6
    # ***
    decoder_depth: 4
    mask_ratio: 0.9
    mask_type: "tube"
    target_type: ${model.net.target_type}
    loss_func: "SWAV"
    memory_size: 0
    num_prototypes: 3000
    sinkhorn_iterations: 10
    eps: 0.03
    kwindow: 1
    # ***
    decoder_num_classes: ${model.net.target_encoder.output_dim} 
    # *** 
    world_size: 1

pretrained: true
ckpt_kwargs: 
  ckpt: ???


