pretrain:
  enc_checkpoint_key: encoder
  pred_checkpoint_key: predictor
  model_name: vit_huge
  patch_size: 16
  folder: /home/diego.canez/checkpoints/intphys/jepa
  checkpoint: vith16.pth.tar
  write_tag: jepa_vith
  use_sdpa: true
  use_silu: true
  wide_silu: false
  uniform_power: true
  is_causal: false
  pred_is_causal: false
  pred_depth: 12
  tubelet_size: 2
  frames_per_clip: 16
data:
  batch_size: 1
  resolution: 224
  stride_sliding_window: 2
  use_bfloat16: true
  frames_per_clip: 32
  context_lengths: [4,8,12,16,20]
  frame_steps: 5
tag: jepa_vith
nodes: 1
tasks_per_node: 1
eval_name: intuitive_physics
dataset: inflevel