pretrain:
  enc_checkpoint_key: model
  pred_checkpoint_key: predictor
  model_name: pretrain_sigma_base_patch16_224
  patch_size: 16
  folder: /home/diego.canez/checkpoints/intphys/sigma
  checkpoint: ssv2_vit_b_sigma_with_dino.pth
  write_tag: sigma_dino_cesk_ssv2
  use_sdpa: true
  uniform_power: true
  is_causal: false
  pred_is_causal: false
  pred_depth: 12
  tubelet_size: 2
  frames_per_clip: 16
data:
  batch_size: 1
  resolution: 224
  stride_sliding_window: 2
  use_bfloat16: true
  frames_per_clip: 32
  context_lengths: [4,8,12,16,20]
  frame_steps: 5
dataset: inflevel_lab
tag: sigma_dino_cesk_ssv2
nodes: 1
tasks_per_node: 1
eval_name: intuitive_physics
is_sigma: true
sigma_target_enc: dino
sigma_loss_type: cross_entropy_sk